### ISSUE TITLE
NOT WORKING AS INIDCATED

### ISSUE THREAD

**Issue by michaelSOLERbeatty** [shephertz/AppWarpUnity#1]
I have downloaded and tested:

Error building Player: SystemException: 'System.Net.Sockets' are supported only with Unity Android Pro. Referenced from assembly 'AppWarpUnity'.

I would realkly appreciate some help:

michael.soler.beatty@gmail.com

**Comment by SuyashMShepHertz** [comment]
Hi,

You need to use the mobile version of AppWarp dll when building for iOS/Android and WP version of AppWarp for Windows Phone. Also make sure, you have places the Plugins folder for AppWarp at root directory. 

Thanks

**Comment by SuyashMShepHertz** [comment]
Hi,

You need to use the mobile version of AppWarp dll when building for iOS/Android and WP version of AppWarp for Windows Phone. Also make sure, you have placed the Plugins folder for AppWarp at root directory. 

Thanks
